version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # db:
  #   image: "docker.io/library/sqlite:latest"
  #   volumes:
  #     - .:/data
  #   command: sqlite3 /data/app.db
