"""add telefoonnummer to schoonmaker

Revision ID: deba43402e24
Revises: cffe24179204
Create Date: 2023-10-14 23:45:46.276242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'deba43402e24'
down_revision: Union[str, None] = 'cffe24179204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schoonmaker', sa.Column('telefoonnummer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schoonmaker', 'telefoonnummer')
    # ### end Alembic commands ###
